name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev
        
    - name: Run tests
      run: |
        pipenv run test

    - name: Run lint
      run: |
        pipenv run lint
